# Site settings
title: VocabHunter
description:
  VocabHunter helps learners of foreign languages hunt for new vocab in documents
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vocabhunter.github.io" # the base hostname & protocol for your site
logo: /assets/VocabHunter-Logo.png

twitter:
  username: vocabhunterapp
  link: https://twitter.com/vocabhunterapp

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown

release_version: 1.0.18

